### ISSUE TITLE
Skin CologneBlue failed to upgrade

### ISSUE THREAD

**Issue by CodyRWhite** [RazeSoldier/mwExtUpgrader#11]
In UpgradeTask.php line 156:
                                                                                                                       
  file_get_contents(/var/www/html/skins/CologneBlue/extension.json): failed to open stream: No such file or directory  
                                                                                                                       

exec:update

**Comment by CodyRWhite** [comment]
Looks like there is no extensions.json but a skins.json

**Comment by RazeSoldier** [comment]
The bug fix is included in [0.1.2 release](https://github.com/RazeSoldier/mwExtUpgrader/releases/tag/v0.1.2).
