### ISSUE TITLE
Failed to Open Stream

### ISSUE THREAD

**Issue by ohheyrj** [RazeSoldier/mwExtUpgrader#13]
Hello, when I run mwExtUpgrader I get the following error:

```
In ErrorChunk.php line 64:

  fopen(https://91.198.174.192/w/api.php?action=query&list=extdistbranches&format=json&formatversion=2&edbexts=ExtensionDistributor%7C): failed to open stream: Failed to parse address "0"

In NativeResponse.php line 114:

  fopen(https://91.198.174.192/w/api.php?action=query&list=extdistbranches&format=json&formatversion=2&edbexts=ExtensionDistributor%7C): failed to open stream: Failed to parse address "0"

exec:update
```

I'm currently running MW 1.35. I wasn't sure where the IP 91.198.174.192 is coming from. If you need anything else let me know

**Comment by RazeSoldier** [comment]
It sounds incredible because there is no IP address in the source code.

Can you provide an error output of the command with the -vvv parameter? (`php run.php -vvv`)

**Comment by RazeSoldier** [comment]
As I know `91.198.174.192` is esams datacenter for wikimedia. https://codesearch.wmcloud.org/search/?q=91%5C.198%5C.174%5C.192&i=nope&files=&repos=

**Comment by ohheyrj** [comment]
Opps ignore me, I think I was doing something wrong. Got it working now, dont think it was anything to do with your code :)

**Comment by latchee** [comment]
Hi @rj175 , how did you correct your issue? I am facing the same error:

`In ErrorChunk.php line 64:

  fopen(https://198.35.26.96/w/api.php?action=query&list=extdistbranches&format=json&formatversion=2&edbexts=ExtensionDistributor%7C): failed to open stream: Failed to parse addr
  ess "0"


In NativeResponse.php line 114:

  fopen(https://198.35.26.96/w/api.php?action=query&list=extdistbranches&format=json&formatversion=2&edbexts=ExtensionDistributor%7C): failed to open stream: Failed to parse addr
  ess "0"


exec:update`
