### ISSUE TITLE
Any plans to support web-based updating?

### ISSUE THREAD

**Issue by hamishmb** [RazeSoldier/mwExtUpgrader#15]
Hi there,

I have a mediawiki site and could benefit from this, but I don't have commandline access. Are there any plans to have a web-based updater?

Thanks,
Hamish

**Comment by RazeSoldier** [comment]
There are currently no relevant plans.

If your host provider does not support allowing you to access the shell, mean that the provider is not a good choice. It is recommended to change to a provider that supports shell access.

 See also https://www.mediawiki.org/wiki/Manual:FAQ#Does_MediaWiki_require_shell_access

**Comment by hamishmb** [comment]
Fair enough. There is however a maintenance shell option that works for almost everything, and is maintained despite the warnings: https://www.mediawiki.org/wiki/Extension:MaintenanceShell.
