### ISSUE TITLE
Possible infinite loop

### ISSUE THREAD

**Issue by kirrus** [RazeSoldier/mwExtUpgrader#17]
Hi,

I noticed this try catch loop;
```
		retry:
		try {
			$task->download();
		} catch (\RuntimeException $e) {
			$output->writeln($e->getMessage());
			goto retry;
		}
```
https://github.com/RazeSoldier/mwExtUpgrader/blob/master/includes/UpgradeTask.php#L100

This could potentially lead to a malfunctioning server serving a mis-sized item, with no way for the code to detect. Might it be worth adding a retry counter & limit?

**Comment by RazeSoldier** [comment]
I removed retry-goto block, use `for` loops instead
