### ISSUE TITLE
Incompatible with PHP 8.1

### ISSUE THREAD

**Issue by kirrus** [RazeSoldier/mwExtUpgrader#18]
Throws the following error;
`
PHP Fatal error:  During inheritance of IteratorAggregate: Uncaught ErrorException: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///home/pzwiki/mwExtUpgrader.phar/vendor/symfony/console/Helper/HelperSet.php:103
`

**Comment by RazeSoldier** [comment]
I created a [release](https://github.com/RazeSoldier/mwExtUpgrader/releases/tag/v0.2) that includes the latest upstream. Can be fix compatibility issues with PHP 8.x.

**Comment by kirrus** [comment]
Confirmed, runs fine with 8.1 now, thanks!
