### ISSUE TITLE
Doesn't handle extension download 404ing

### ISSUE THREAD

**Issue by kirrus** [RazeSoldier/mwExtUpgrader#19]
Appears to upgrade all others fine. Additionally, the released version just threw the Undefined Array exception, without telling me which extension it was getting stuck on -- had to grab the git repo version to get it to show me the failed url

```
Undefined array key "content-length"
Undefined array key "content-length"
  Failed to download from https://extdist.wmflabs.org/dist/extensions/Math-REL1_39-88f35be.tar.gz  
```

Otherwise, thank you for this tool! It makes updating MediaWiki a *lot* less painful :partying_face:

**Comment by kirrus** [comment]
Specifically, it appears this is because the generated download link returned 404s at the time -- so the issue may be that the upgrader can't handle if the provided extension download link is not found

**Comment by RazeSoldier** [comment]
Which links returns 404?

**Comment by kirrus** [comment]
Was the generated download link for Math extension https://extdist.wmflabs.org/dist/extensions/Math-REL1_39-88f35be.tar.gz

**Comment by RazeSoldier** [comment]
For me, looks like it is 200:
```
# curl https://extdist.wmflabs.org/dist/extensions/Math-REL1_39-88f35be.tar.gz -I
HTTP/1.1 200 OK
Server: nginx/1.18.0
Date: Wed, 15 Mar 2023 14:40:13 GMT
Content-Type: application/octet-stream
Content-Length: 634772
Connection: keep-alive
Last-Modified: Wed, 15 Mar 2023 14:11:41 GMT
ETag: "6411d21d-9af94"
Accept-Ranges: bytes
Strict-Transport-Security: max-age=31622400
X-Clacks-Overhead: GNU Terry Pratchett
```

**Comment by kirrus** [comment]
Looks like it's 200 now for me as well. Probably just a temporary issue

**Comment by kirrus** [comment]
I've tested this now, by appending adding a breaking string to the $this->url variable in the make request functions in includes/DownloadTask.php, the script now throws a 'failed to download' warning. Closing issue, thanks again
