### ISSUE TITLE
No information of the updated version

### ISSUE THREAD

**Issue by aseques** [RazeSoldier/mwExtUpgrader#4]
It would be nice if you got a message telling you the previous version of the extension and the one that has been replaced with, currently it outputs as:

```

Will be upgraded 25 extensions.
----------------------
(1/25)[Renameuser extension] Done. 
----------------------
(2/25)[ParserFunctions extension] Done. 
----------------------
(3/25)[WikiEditor extension] Done. 
----------------------
(4/25)[ImageMap extension] Done. 
----------------------
(5/25)[LDAPAuthorization extension] Done. 
----------------------
(6/25)[ReplaceText extension] Done. 
----------------------
(7/25)[SyntaxHighlight_GeSHi extension] Done. 
----------------------
(8/25)[LDAPProvider extension] Done. 
----------------------
(9/25)[ConfirmEdit extension] Done. 
----------------------
(10/25)[CiteThisPage extension] Done. 
----------------------
(11/25)[PdfHandler extension] Done. 
----------------------
(12/25)[Interwiki extension] Done. 
----------------------
(13/25)[SpamBlacklist extension] Done. 
----------------------
(14/25)[InputBox extension] Done. 
----------------------
(15/25)[Nuke extension] Done. 
----------------------
```

**Comment by aseques** [comment]
With the current code would show as:
```Renameuser upgrade successed
ParserFunctions upgrade successed
WikiEditor upgrade successed
ImageMap upgrade successed
LDAPAuthorization upgrade successed
ReplaceText upgrade successed
SyntaxHighlight_GeSHi upgrade successed
LDAPProvider upgrade successed
ConfirmEdit upgrade successed
CiteThisPage upgrade successed
PdfHandler upgrade successed
Interwiki upgrade successed
SpamBlacklist upgrade successed
```

**Comment by RazeSoldier** [comment]
Considering that it is currently not possible to know the version from the extension file, I plan to display the version to be upgraded before upgrading.

**Comment by aseques** [comment]
No sure if it't what you need, but there's a version inside every extension with the version:
```
for i in `find . -name "extension.json"` ; do
  grep -H '"version":' $i
done
```

For example would output in my case:

> ./ParserFunctions/extension.json:       "version": "1.6.0",
> ./WikiEditor/extension.json:    "version": "0.5.2",
> ./LDAPAuthorization/extension.json:     "version": "1.0.0",
> ./ReplaceText/extension.json:   "version": "1.4.1",
> ./SyntaxHighlight_GeSHi/extension.json: "version": "2.0",
> ./LDAPProvider/extension.json:  "version": "1.0.0",
> ./ConfirmEdit/extension.json:   "version": "1.6.0",
> ./Interwiki/extension.json:     "version": "3.1 20160307",
> ./InputBox/extension.json:      "version": "0.3.0",
> ./Nuke/extension.json:  "version": "1.3.0",
> ./OATHAuth/extension.json:      "version": "0.2.2",
> ./Cite/extension.json:  "version": "1.0.0",
> ./TitleBlacklist/extension.json:        "version": "1.5.0",
> ./LocalisationUpdate/extension.json:    "version": "1.4.0",
> ./PluggableAuth/extension.json: "version": "5.7",

**Comment by RazeSoldier** [comment]
I know what you mean. But not all extensions have extension.json, and not every extension.json contains `version` field. Does showing the version change benefit the end user?

Instead of depend on the extension version to get updates, we depend on the version of MediaWiki.

**Comment by aseques** [comment]
Not really a benefit, but a more verbose output such as apt-get (replacing version x.xx with version y.yy) make it a bit more informative (i.e. showing you if there's a big jump in versions) and for the ones with a proper version tag you might skip the update when the version is the same.
But you know much better mediawiki that me, so do what makes more sense

**Comment by RazeSoldier** [comment]
Will do. But won't come soon.

**Comment by RazeSoldier** [comment]
Now, each an extension is successfully upgraded, the version will be output. If there is no recorded version in composer.json, it will not be output.
